- name: Deploy vm in Azure Cloud
  hosts: localhost
  connection: local
  vars:

  tasks:
  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts
  
  #- include_role:
  #    name: ansible_azure_vm