- name: Print public IP of the HAProxy host
  hosts: haproxy
  become: true
  vars:

  tasks:
  - name: Print public IP of the HAProxy host
    ansible.builtin.debug:
      msg: "The Cool Lab App can be reached at: {{ ansible_host }}"
    