---
# This playbook does a rolling update for all servers serially (one at a time).
# Change the value of serial: to adjust the number of server to be updated.
#
#
- hosts: frontend
  become: true
  serial: 1
  tasks:
  - name: "Ensure {{ inventory_hostname }} is disabled in HAProxy"
    ansible.builtin.haproxy:
      state: disabled
      backend: habackend
      host: "{{ inventory_hostname }}"
      socket: /var/lib/haproxy/stats
    delegate_to: "{{ item }}"
    with_items: "{{ query('inventory_hostnames', 'haproxy') }}"

  - name: Include role cool_lab_app
    ansible.builtin.include_role:
      name: cool_lab_app

  - name: "Ensure cool lab app responds after update."
    ansible.builtin.wait_for:
      host: "{{ ansible_host }}"
      port: "{{ cool_lab_app_port }}"
      state: started
      timeout: 80

  - name: "Ensure {{ inventory_hostname }} is enabled in HAProxy."
    ansible.builtin.haproxy:
      state: enabled
      backend: habackend
      host: "{{ inventory_hostname }}"
      socket: /var/lib/haproxy/stats
    delegate_to: "{{ item }}"
    with_items: "{{ query('inventory_hostnames', 'haproxy') }}"
